### ISSUE TITLE
Network serial 

### ISSUE THREAD

**Issue by deformedchild** [sprocket-9/nuvo-serial#1]
any chance of support for network serial thanks

**Comment by sprocket-9** [comment]
If you use port_url="socket://host:port"  it should just work for you.  I didn't put anything in the docs as I hadn't tested at the time, but I had a need to try it the other day and it worked fine.  

I used ser2net with a config of:
10003:raw:0:/dev/nuvo:57600 8DATABITS NONE 1STOPBIT
